/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Legacy aliases (still used in a few pages) — kept, re-pointed where needed
        bg: 'var(--bg)',
        surface: '#f9f9ff',
        text: 'var(--text)',
        muted: 'var(--textMuted)',
        border: 'var(--border)',
        accent: 'var(--accent)',
        accent2: 'var(--accent2)',
        brand: {
          DEFAULT: '#2563eb',
          light: '#3b82f6',
          dark: '#1e40af',
          ink: '#0b1220',
          cyan: '#22d3ee',
          violet: '#a78bfa',
        },
        // "DELFluent Academic" M3 token set (from stitch DESIGN.md)
        primary: '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        secondary: '#674bb5',
        'on-secondary': '#ffffff',
        'secondary-container': '#ab8ffe',
        'on-secondary-container': '#3f1e8c',
        'secondary-fixed': '#e8ddff',
        'secondary-fixed-dim': '#cebdff',
        tertiary: '#005e6b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007889',
        'on-tertiary-container': '#d2f6ff',
        'tertiary-fixed': '#a2eeff',
        'tertiary-fixed-dim': '#2fd9f4',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#d3daee',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e2e8fc',
        'surface-container-highest': '#dce2f6',
        'surface-variant': '#dce2f6',
        'on-surface': '#151b2a',
        'on-surface-variant': '#434655',
        'on-background': '#151b2a',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'inverse-surface': '#2a3040',
        'inverse-primary': '#b4c5ff',
        'surface-tint': '#0053db',
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        serif: ['"Source Serif 4"', 'Source Serif Pro', 'Georgia', 'serif'],
      },
      // Type roles from DESIGN.md
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '22px' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'passage-serif': ['17px', { lineHeight: '30.6px', letterSpacing: '0.01em' }],
        'passage-serif-mobile': ['19px', { lineHeight: '34px' }],
      },
      boxShadow: {
        'level-1': '0 6px 18px rgba(15, 23, 42, 0.06)',
        'level-2': '0 14px 44px rgba(15, 23, 42, 0.10)',
      },
      maxWidth: {
        container: '1152px',
      },
    },
  },
  plugins: [],
};
